# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
julia:
    - 0.7
    - 1.0
    - nightly
matrix:
    allow_failures:
        - julia: nightly
notifications:
    email: false
sudo: false
before_install:
    - (sudo apt-get -qq update && sudo apt-get install -y python3 python3-matplotlib)
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia --color=yes -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("Modia"); Pkg.test("Modia"; coverage=true)';
after_success:
    - julia --color=yes -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder());'
